const mongoose = require("mongoose");
const { Schema } = mongoose;

const resourceSchema = new Schema({
	title: String,
	icon: String,
	iconVersion: String,
	videos: [{ title: String, url: String }],
	link: String,
});
const textbookSchema = new Schema({
	title: String,
	author: [String],
	chapters: [
		{
			title: String,
			number: Number,
			text: String,
			image: String,
		},
	],
});
const courseSchema = new Schema({
	name: String,
	lessons: [
		{
			ProblemStepID: String,
			StepUID: String,
			Problem: String,
			ProblemID: String,
			FunctionUID: String,
			AudioPath: String,
			VideoPath: String,
			A1: String,
			A2: String,
			A3: String,
			A4: String,
			A5: String,
			A6: String,
			A7: String,
			A8: String,
			A9: String,
			A10: String,
			A1_Alt: String,
			A2_Alt: String,
			A3_Alt: String,
			A4_Alt: String,
			A5_Alt: String,
			A6_Alt: String,
			A7_Alt: String,
			A8_Alt: String,
			A9_Alt: String,
			A10_Alt: String,
			Audio_Alt: String,
			ProbFlag: String,
			InstrFlag: String,
			ExamFlag: String,
			PlusMode: String,
			NormalMode: String,
			MinusMode: String,
			Archived: String,
			ProblemStepNumber: String,
			ConsoleID: String,
			LearnFlag: String,
			ConsoleName: String,
			ConsoleFile: String,
			ConsoleStyle: String,
			ConsoleUID: String,
			RecNo: String,
			MonitorStatus: String,
			LastActivity: String,
			Comment: String,
			CourseID: String,
			DisplayCourseID: String,
			ExamCount: String,
			ExamPositionUID: String,
			WrongCount: String,
			RightInARow: String,
			SetBackFlag: String,
			SetBackVideo: String,
			CourseMode: String,
			AssignmentID: String,
			RetakeFlag: Number,
			StepUpdate: String,
			ServerID: String,
			IntServer: String,
			ClassID: Number,
			EnrollDate: String,
			WeeklyGoal: String,
			FinishGoal: String,
			StepNumber: String,
			MultiMode: String,
			RecoveryMode: String,
			ExamRecovery: String,
			UnitRecovery: String,
			VideoPosition: String,
			LastApprovedStepID: String,
			AutoSave: String,
			LessonLimitFlag: Number,
			StepRepeatCount: String,
			RecoveryCompleted: String,
			SuccessZone: String,
			GoalCompleted: Number,
			HighestExamScore: String,
			HighestLessonScore: String,
			DaysAbsent: String,
			KeepInCourse: String,
			FirstTouch: String,
			ProblemsRemaining: Number,
			PercentComplete: Number,
			UID: String,
			AA: String,
			AB: String,
			AC: String,
			AD: String,
			AE: String,
			AF: String,
			AG: String,
			AH: String,
			AI: String,
			AJ: String,
			AK: String,
			AL: String,
			AM: String,
			AN: String,
			AO: String,
			AP: String,
			AQ: String,
			AR: String,
			AT: String,
			AU: String,
			AV: String,
			AW: String,
			AX: String,
			AY: String,
			AZ: String,
			BA: String,
			BB: String,
			BC: String,
			BD: String,
			BE: String,
			BF: String,
			BG: String,
			BH: String,
			BI: String,
			BJ: String,
			ArchivedStepNo: String,
			AudioFlagOptional: String,
			ArchivedDate: String,
			Status: String,
			ProblemStatus: String,
			ClearStats: String,
			stepLink: String,
			FuncType: String,
			ClassName: String,
			ShowSkip: Number,
			LastAnswer: String,
			LastFuncType: String,
			ImageCache: String,
			copyrightYear: String,
			MediaServer: String,
			FallBackServer: String,
			FunctionType: String,
		},
	],
});
const feedbackSchema = new Schema({
	name: String,
	message: String,
	date: String,
});
module.exports = { courseSchema, resourceSchema, textbookSchema, feedbackSchema };
